apiVersion: chaos-mesh.org/v1alpha1
kind: PhysicalMachineChaos
metadata:
  name: physical-network-delay
  namespace: chaos-mesh
spec:
  action: network-delay
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      'arch': 'amd64'
  network-delay:
    device: ens33
    ip-address: 140.82.112.3
    latency: 1000ms
  duration: '10m'